version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=sqlite:///todo.db
    volumes:
      - ./backend:/app
      - todo_data:/app/data
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    restart: unless-stopped

volumes:
  todo_data:
